DROP TABLE IF EXISTS ARTISTTABLE;
DROP TABLE IF EXISTS PERSONTABLE;
DROP TABLE IF EXISTS STUDIOSTABLE;
DROP TABLE IF EXISTS LOCATIONTABLE;
DROP TABLE IF EXISTS URLTABLE;
DROP TABLE IF EXISTS SONGTABLE;
DROP TABLE IF EXISTS GENRETABLE;
DROP TABLE IF EXISTS INSTRUMENTTABLE;
DROP TABLE IF EXISTS AWARDTABLE;
DROP TABLE IF EXISTS ALBUMTABLE;
DROP TABLE IF EXISTS FESTIVALTABLE;
DROP TABLE IF EXISTS LYRICSTABLE;
DROP TABLE IF EXISTS USERTABLE;

CREATE TABLE ALBUMTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(80) NOT NULL,YEAR INTEGER NOT NULL,SONGNUMBER INTEGER,STUDIO VARCHAR(44), ARTIST VARCHAR(44));
CREATE TABLE FESTIVALTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(40) NOT NULL,TARIH INTEGER, LOCATION VARCHAR(44));
CREATE TABLE LYRICSTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,ORIGINAL VARCHAR(40) NOT NULL,CONVERT INTEGER);
CREATE TABLE PERSONTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(40),SURNAME VARCHAR(32), AGE INTEGER, BAND VARCHAR(44), LOCATION VARCHAR(45), INSTRUMENT VARCHAR(44));
CREATE TABLE ARTISTTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(80),GENRE VARCHAR(80),MEMBERNUMBER INTEGER,NAME2 VARCHAR(200),SURNAME2 VARCHAR(200), URL VARCHAR(40));
CREATE TABLE STUDIOSTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(40) NOT NULL,LOCATION VARCHAR(40),OWNER VARCHAR(29) NOT NULL,FOUNDATIONDATE INTEGER,ARTIST VARCHAR(40) NOT NULL,LINK VARCHAR(50) NOT NULL);
CREATE TABLE LOCATIONTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,CONTINENT VARCHAR(40) NOT NULL,COUNTRY VARCHAR(40) NOT NULL,TOWN VARCHAR(55) NOT NULL);
CREATE TABLE URLTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(55) NOT NULL,WIKI VARCHAR(55) NOT NULL,FACEBOOK VARCHAR(55),TWITTER VARCHAR(55) NOT NULL, YOUTUBE VARCHAR(32));
CREATE TABLE SONGTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(40) NOT NULL,LYRIC VARCHAR(200) NOT NULL,LINK VARCHAR(55) NOT NULL,ALBUM VARCHAR(44));
CREATE TABLE GENRETABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(40) NOT NULL,INSTRUMENT VARCHAR(40) NOT NULL, LOCATION VARCHAR(55) NOT NULL, INFO VARCHAR(55) NOT NULL, AWARD VARCHAR(45));
CREATE TABLE INSTRUMENTTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(40) NOT NULL,TYPE VARCHAR(40) NOT NULL,RANGE VARCHAR(55) NOT NULL,LOCATION VARCHAR(55) NOT NULL , LOCATION1 VARCHAR(55), LOCATION2 VARCHAR(55) );
CREATE TABLE AWARDTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME VARCHAR(40) NOT NULL,LOCATION VARCHAR(40),TYPE VARCHAR(40) NOT NULL,YEAR INTEGER,ARTIST VARCHAR(40));
CREATE TABLE USERTABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,USERNAME VARCHAR(20) NOT NULL, PASSWORD VARCHAR(32) NOT NULL, NAME VARCHAR(20) NOT NULL, SURNAME VARCHAR(20) NOT NULL, BIRTHDAY DATE NOT NULL, AUTHLEVEL VARCHAR(1) NOT NULL);

ALTER TABLE PERSONTABLE ADD COLUMN FK_BAND INTEGER REFERENCES ARTISTTABLE(ID);
ALTER TABLE ALBUMTABLE ADD COLUMN FK_STUDIO INTEGER REFERENCES STUDIOSTABLE(ID);
ALTER TABLE SONGTABLE ADD COLUMN FK_ALBUM INTEGER REFERENCES ALBUMTABLE(ID);
ALTER TABLE SONGTABLE ADD COLUMN FK_LYRIC INTEGER REFERENCES LYRICSTABLE(ID);
ALTER TABLE SONGTABLE ADD COLUMN FK_LINK INTEGER REFERENCES LINKTABLE(ID);
ALTER TABLE STUDIOSTABLE ADD COLUMN FK_LOCATION INTEGER REFERENCES LOCATIONTABLE(ID);
ALTER TABLE FESTIVALTABLE ADD COLUMN FK_LOCATION INTEGER REFERENCES LOCATIONTABLE(ID);
ALTER TABLE GENRETABLE ADD COLUMN FK_AWARD INTEGER REFERENCES AWARDTABLE(ID);
ALTER TABLE AWARDTABLE ADD COLUMN FK_ARTIST INTEGER REFERENCES ARTISTTABLE(ID);
ALTER TABLE ARTISTTABLE ADD COLUMN FK_URL INTEGER REFERENCES URLTABLE(ID);
ALTER TABLE ARTISTTABLE ADD COLUMN FK_GENRE INTEGER REFERENCES GENRETABLE(ID);
ALTER TABLE ALBUMTABLE ADD COLUMN FK_ARTIST INTEGER REFERENCES ARTISTTABLE(ID);
ALTER TABLE PERSONTABLE ADD COLUMN FK_LOCATION INTEGER REFERENCES LOCATIONTABLE(ID);
ALTER TABLE PERSONTABLE ADD COLUMN FK_INSTRUMENT INTEGER REFERENCES INSTRUMENTTABLE(ID);
ALTER TABLE INSTRUMENTTABLE ADD COLUMN FK_LOCATION INTEGER REFERENCES LOCATIONTABLE(ID);

INSERT INTO USERTABLE (USERNAME, PASSWORD, NAME, SURNAME, BIRTHDAY, AUTHLEVEL) VALUES('testU', '098f6bcd4621d373cade4e832627b4f6', '-', '-', '549925200000', 'U');
INSERT INTO USERTABLE (USERNAME, PASSWORD, NAME, SURNAME, BIRTHDAY, AUTHLEVEL) VALUES('test', '098f6bcd4621d373cade4e832627b4f6', '-', '-', '549925200000', 'U');
INSERT INTO USERTABLE (USERNAME, PASSWORD, NAME, SURNAME, BIRTHDAY, AUTHLEVEL) VALUES('emre', '6aadb07bcd9a9a347f2a38628de99c7b', 'Emre', 'EROĞLU', '549925200000', 'A');

INSERT INTO LOCATIONTABLE(CONTINENT, COUNTRY, TOWN) VALUES('Scandinavia', 'Sweden', 'Tumba');
INSERT INTO LOCATIONTABLE(CONTINENT, COUNTRY, TOWN) VALUES('United States', 'California', 'Glendale');


INSERT INTO ARTISTTABLE (NAME, GENRE, MEMBERNUMBER, NAME2, SURNAME2, URL, FK_URL, FK_GENRE) VALUES('Metallica', 'Heavy Metal', '4', ' ', ' ', 'http://tr.wikipedia.org/wiki/Metallica', ' ', ' ');
INSERT INTO ARTISTTABLE (NAME, GENRE, MEMBERNUMBER, NAME2, SURNAME2, URL, FK_URL, FK_GENRE) VALUES('Nirvana', 'Alternative Rock', '5', ' ', ' ', 'http://tr.wikipedia.org/wiki/Nirvana_(m%C3%BCzik_grubu)', ' ', ' ');
INSERT INTO ARTISTTABLE (NAME, GENRE, MEMBERNUMBER, NAME2, SURNAME2, URL, FK_URL, FK_GENRE) VALUES('Guns N Roses', 'Hard Rock', '5', ' ', ' ', 'http://tr.wikipedia.org/wiki/Guns_N%27_Roses', ' ', ' ' );



INSERT INTO PERSONTABLE (NAME, SURNAME, AGE, BAND, LOCATION, INSTRUMENT, FK_BAND, FK_LOCATION, FK_INSTRUMENT) VALUES('James', 'Hetfield', '51','Metallica', 'A', 'B','1', '99999', '99999');
INSERT INTO PERSONTABLE (NAME, SURNAME, AGE, BAND, LOCATION, INSTRUMENT, FK_BAND, FK_LOCATION, FK_INSTRUMENT) VALUES('Kurt', 'Cobain', '27', 'Nirvana', 'C' , 'd','2', '99999', '999999');
INSERT INTO PERSONTABLE (NAME, SURNAME, AGE, BAND, LOCATION, INSTRUMENT, FK_BAND, FK_LOCATION, FK_INSTRUMENT) VALUES('Saul Hudson', 'SLASH', '49', 'Guns N Roses', 'E' , 'f','3', '99999', '999999');


INSERT INTO ALBUMTABLE (NAME, YEAR, SONGNUMBER, STUDIO, ARTIST, FK_STUDIO, FK_ARTIST) VALUES('Ride the Lightning', '1984', '12','Sweet Silence Studios','Metallica','1','9999');
INSERT INTO ALBUMTABLE (NAME, YEAR, SONGNUMBER, STUDIO, ARTIST, FK_STUDIO, FK_ARTIST) VALUES('...And Justice for All', '1988', '13','"One On One" Stüdyoları','Metallica','1','9999');
INSERT INTO ALBUMTABLE (NAME, YEAR, SONGNUMBER, STUDIO, ARTIST, FK_STUDIO, FK_ARTIST) VALUES('Nevermind', '1991', '7','Smart Studios','Nirvana','2','9999');
INSERT INTO ALBUMTABLE (NAME, YEAR, SONGNUMBER, STUDIO, ARTIST, FK_STUDIO, FK_ARTIST) VALUES('In Utero', '1993', '7','Pachyderm Studios','Nirvana','2','9999');

INSERT INTO URLTABLE (NAME, WIKI, TWITTER, FACEBOOK, YOUTUBE) VALUES('name', 'http://en.wikipedia.org/wiki/Justin_Timberlake', 'https://twitter.com/jtimberlake', 'https://www.facebook.com/justintimberlake', 'http://www.youtube.com/user/JustinTimberlake');
INSERT INTO URLTABLE (NAME, WIKI, TWITTER, FACEBOOK, YOUTUBE) VALUES('name1', 'http://en.wikipedia.org/wiki/Pump_It', '-', '-', 'http://www.youtube.com/watch?v=ZaI2IlHwmgQ');
INSERT INTO URLTABLE (NAME, WIKI, TWITTER, FACEBOOK, YOUTUBE) VALUES('name2', 'http://en.wikipedia.org/wiki/Swamplord', '-', '-', 'http://www.youtube.com/watch?v=-aPK5kYGsQs');

INSERT INTO SONGTABLE (NAME, LYRIC, LINK, ALBUM, FK_ALBUM, FK_LYRIC, FK_LINK) VALUES('Fear of the Dark', 'When the light begins to change, I sometimes feel a little strange, A little anxious when its dark.', 'http://www.youtube.com/watch?v=Nba3Tr_GLZU', 'Album', '1',' ',' ');
INSERT INTO SONGTABLE (NAME, LYRIC, LINK, ALBUM, FK_ALBUM, FK_LYRIC, FK_LINK) VALUES('Here Comes The Rain Again', 'I want to walk in the open wind, I want to talk like the lovers do, I want to dive into your ocean, Is it raining with you?', 'http://www.youtube.com/watch?v=5-juDiDTYfw', 'Album', '2',' ',' ');
INSERT INTO SONGTABLE (NAME, LYRIC, LINK, ALBUM, FK_ALBUM, FK_LYRIC, FK_LINK) VALUES('Litaliano', 'Lasciatemi cantare, con la chitarra e mano, lasciatemi cantare, una canzone piano piano, Lasciatemi cantare, perché ne sono fiero, sono litaliano, litaliano vero', 'http://www.youtube.com/watch?v=ZvA1utmKVxM' ,'Album', '3',' ',' ');

INSERT INTO AWARDTABLE (NAME, LOCATION, TYPE, YEAR, ARTIST) VALUES('Grammy', 'Tumba', 'asd', '2014', 'cobain');


INSERT INTO GENRETABLE (NAME, INSTRUMENT, LOCATION, INFO, AWARD) VALUES('Grammy', 'Tumba', 'asd', '2014', 'cobain');

