INSERT INTO LOCATIONTABLE(CONTINENT, COUNTRY, TOWN) VALUES('United States', 'California', 'Los Angeles');
INSERT INTO LOCATIONTABLE(CONTINENT, COUNTRY, TOWN) VALUES('Scandinavia', 'Sweden', 'Tumba');
INSERT INTO LOCATIONTABLE(CONTINENT, COUNTRY, TOWN) VALUES('United States', 'California', 'Glendale');